from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView
from .views import (base_view,
                    category_view,
                    product_view,
                    cart_view,
                    add_to_cart_view,
                    remove_from_cart_view,
                    change_item_qty,
                    check_out_view,
                    order_create_view,
                    make_order_view,
                    account_view,
                    registration_view,
                    login_view,
                    orders_graf,
                    products_graf,
                    UserOrdersGrafView,
                    products_sales_graf,
                    category_graf,
                    sales_forecasting,
                    category_sales_forecasting,
                    product_sales_forecasting,
                    user_sales_forecasting,
                    clusters_num,
                    cluster_analysis,
                    message,
                    coffee_zer_mail,
                    coffee_molot_mail,
                    coffee_rastvor_mail,
                    tea_paket_mail,
                    tea_listov_mail,
                    message_for_new_year,
                    )


urlpatterns = [
    url(r'^category/(?P<category_slug>[-\w]+)/$', category_view, name='category_detail'),
    url(r'^product/(?P<product_slug>[-\w]+)/$', product_view, name='product_detail'),
    url(r'^add_to_cart/$', add_to_cart_view, name='add_to_cart'),
    url(r'^remove_from_cart/$', remove_from_cart_view, name='remove_from_cart'),
    url(r'^change_item_qty/$', change_item_qty, name='change_item_qty'),
    url(r'^cart/$', cart_view, name='cart'),
    url(r'^check_out/$', check_out_view, name='check_out'),
    url(r'^order/$', order_create_view, name='create_order'),
    url(r'^make_order/$', make_order_view, name='make_order'),
    url(r'^thank_you/$', TemplateView.as_view(template_name='thank_you.html'), name='thank_you'),
    url(r'graph1', TemplateView.as_view(template_name='graph1.html'), name='graph1'),
    url(r'^graph2/$', TemplateView.as_view(template_name='graph2.html'), name='graph2'),
    url(r'^graph3/$', TemplateView.as_view(template_name='graph3.html'), name='graph3'),
    url(r'^account/$', account_view, name='account'),
    url(r'^registration/$', registration_view, name='registration'),
    url(r'^login/$', login_view, name='login'),
    url(r'^logout/&', LogoutView.as_view(next_page='base'), name='logout'),
    url(r'^order_graf/$', orders_graf, name='orders_graf'),
    url(r'^products_graf/$', products_graf, name='products_graf'),
    url(r'^user_orders_graf/$', UserOrdersGrafView.as_view(), name='user_orders_graf'),
    url(r'^products_sales_graf/$', products_sales_graf, name='products_sales_graf'),
    url(r'^category_graf/$', category_graf, name='category_graf'),
    url(r'^sales_forecasting/$', sales_forecasting, name='sales_forecasting'),
    url(r'^category_sales_forecasting/$', category_sales_forecasting, name='category_sales_forecasting'),
    url(r'^product_sales_forecasting/$', product_sales_forecasting, name='product_sales_forecasting'),
    url(r'^user_sales_forecasting/$', user_sales_forecasting, name='user_sales_forecasting'),
    url(r'^clusters_num/$', clusters_num, name='clusters_num'),
    url(r'^cluster_analysis/$', cluster_analysis, name='cluster_analysis'),
    url(r'^message/$', message, name='message'),
    url(r'^mailing_menu/$', TemplateView.as_view(template_name='mailing_menu.html'), name='mailing_menu'),
    url(r'^coffee_zer_mail/$', coffee_zer_mail, name='coffee_zer_mail'),
    url(r'^coffee_molot_mail/$', coffee_molot_mail, name='coffee_molot_mail'),
    url(r'^coffee_rastvor_mail/$', coffee_rastvor_mail, name='coffee_rastvor_mail'),
    url(r'^tea_paket_mail/$', tea_paket_mail, name='tea_paket_mail'),
    url(r'^tea_listov_mail/$', tea_listov_mail, name='tea_listov_mail'),
    url(r'^message_for_new_year/$', message_for_new_year, name='message_for_new_year'),
    url(r'^$', base_view, name='base'),
]
